### ISSUE TITLE
about train omg resolution

### ISSUE THREAD

**Issue by daixiangzi** [taconite/arah-release#15]
if I want to train img_resolution is[2688,1580],can I increase num_fg_samples:2048 or lager?

**Comment by daixiangzi** [comment]
I train my own dataset ,result is blurred. the reason ? num_fg_samples not is enough?train epoch not is enough?
train_frame:300,num_fg_samples:1024,epoch:80

**Comment by daixiangzi** [comment]
I trained 134 epoch ,results well than epoch 80,but still  blurred，I doubt that num_fg_samples not is enough.....

**Comment by taconite** [comment]
Your image resolution is too large, I don't think our code will work out-of-box on that resolution...

You can always increase num_fg_samples (and num_bg_samples as well), but I doubt that is a good solution as you might run out of memory quickly.

I would say a good way to debug the code is to resize your image to a resolution smaller than 1024x1024, and see if you can get reasonable results. If you absolutely need to train on ultra-high resolution images, I think possible solutions are 1) use a more compact representation for SDF and color (e.g. Hashing grids, TensoRF, etc.) so that you can handle more rays simultaneously, 2) use multi-resolution training by distributing your ray samples to different levels of resolutions.

**Comment by daixiangzi** [comment]
> Your image resolution is too large, I don't think our code will work out-of-box on that resolution...
> 
> You can always increase num_fg_samples (and num_bg_samples as well), but I doubt that is a good solution as you might run out of memory quickly.
> 
> I would say a good way to debug the code is to resize your image to a resolution smaller than 1024x1024, and see if you can get reasonable results. If you absolutely need to train on ultra-high resolution images, I think possible solutions are 1) use a more compact representation for SDF and color (e.g. Hashing grids, TensoRF, etc.) so that you can handle more rays simultaneously, 2) use multi-resolution training by distributing your ray samples to different levels of resolutions.

thank you for your reply, I will try to in increase num_fg_sample;but i have other doubt that I think increase num_fg_sample is ok, why increase num_bg_sample? bg_sample is out of mask?more num_bg_sample is not valid?

**Comment by taconite** [comment]
In principle you need to sample from background to learn a reasonable shape. Sample only foreground pixels woulnd't give any good result. I am just hypothesizing that extremely unbalanced fg/bg sample could hurt the SDF learning process, but that's just a claim, you can try it out yourself anyway...

**Comment by daixiangzi** [comment]
> In principle you need to sample from background to learn a reasonable shape. Sample only foreground pixels woulnd't give any good result. I am just hypothesizing that extremely unbalanced fg/bg sample could hurt the SDF learning process, but that's just a claim, you can try it out yourself anyway...

ok,i will increase num_sample on bg and fg
