### ISSUE TITLE
Resolution of training image

### ISSUE THREAD

**Issue by darthgera123** [taconite/arah-release#17]
@taconite My doubt was that I was training on a custom dataset with similar setting as ZJU-MOCAP. However I observed that the images were cropped and in the top left corner and then passed for training as shown here. Is there any reason for such a design decision

**Comment by darthgera123** [comment]
![gt_000098](https://user-images.githubusercontent.com/30871411/214826948-633be873-1c3b-447f-951e-1e4d5d0a020e.png)

**Comment by darthgera123** [comment]
when it should be something like this: 
![gt_000098](https://user-images.githubusercontent.com/30871411/214827034-a5261761-c097-47f1-8e4b-36b0a981d5ab.png)

**Comment by taconite** [comment]
Not sure how you modified the dataloader, at least on ZJU-MoCap I have tried both original resolution (1024x1024) and half resolution (512x512) and it does not produce what you described here.

I updated the dataloader so that the preprocessing logic is much simpler, maybe you can try building your custom dataset on top of the new dataloader and see if the problem persists?

**Comment by taconite** [comment]
Close the issue due to inactivity.
