### ISSUE TITLE
Differences between the 'body_model's of human_body_prior and easymocap?

### ISSUE THREAD

**Issue by Alex-JYJ** [taconite/arah-release#18]
Thanks for your great work! I have some questions about the code:
https://github.com/taconite/arah-release/blob/e28b06fd30f47ee733abe00c5e33a6eb5b33af4a/preprocess_datasets/preprocess_ZJU-MoCap.py#L131-L139
1. Why are the vertex positions obtained by the two `body_model`s different? I didn't find any differences in these two classes and corresponding `lbs` functions.
2. Why you need to change the `new_trans`?

**Comment by taconite** [comment]
There is some subtle difference between EasyMoCap's SMPL and the official SMPL model, described [here](https://github.com/zju3dv/EasyMocap/blob/master/doc/02_output.md#attention-for-smplsmpl-x-users). TL;DR: the difference will result in inconsistency in global translations of the two meshes. Since our model follows the official SMPL model, we need to compensate for the difference in global translation.

**Comment by taconite** [comment]
Close the issue due to inactivity.
