### ISSUE TITLE
What is the lightning_logs?

### ISSUE THREAD

**Issue by sunwonlikeyou** [taconite/arah-release#8]
There is no lightning_logs with my custom data.
How can I get??

**Comment by taconite** [comment]
The folder should be empty

**Comment by sunwonlikeyou** [comment]
Dose that means it isn't necessary to use them to render images with my custom trained models?

**Comment by taconite** [comment]
It's some dummy logging directory created with test.py - the reason is that when running test.py for the demo, I do not use WandbLogger as the logger for PyTorch lightning, as it is too troublesome for users to register wandb if they only want to run the demo. Somehow PyTorch lightning's default logger creates a `lightning_logs` folder, maybe with some automatically generated content, but it was never actually used so you can just ignore it.

For train.py/validate.py the logs are stored in `${model_dir}/wandb`
